In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import scipy

In [3]:
import ssvepcca
from ssvepcca.utils import load_mat_data_array
from ssvepcca.pipelines import test_fit_predict, k_fold_predict
ssvepcca.runtime_configuration.load_from_name("tsinghua-bci-lab")

In [20]:
from ssvepcca.transformers import (
    EEGType,
    StandardCCA,
    StandardCCAFilter,
    FilterbankCCA,
    FBSpatioTemporalCCA,
    FilterbankCCAFilter,
    SpatioTemporalCCA,
    chain_call_transformers,
)

In [5]:
electrode_list_fbcca = ssvepcca.parameters.electrode_list_fbcca

In [6]:
start_time_index = 125
stop_time_index = 375

In [7]:
input_data = load_mat_data_array("../dataset/tsinghua_bci_lab/S2.mat")

In [8]:
input_data.shape

(6, 40, 1500, 64)

## Train with more data

In [29]:
result_cca_fixed_coefficients = k_fold_predict(
    input_data, 
    StandardCCAFilter(
        electrodes_name=electrode_list_fbcca,
        start_time_idx=start_time_index,
        stop_time_idx=stop_time_index,
        num_harmonics=5
    )
)

[block 0] | Started
[block 0] | Fit the learner
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
[block 0] | Predict on test data
[block 1] | Started
[block 1] | Fit the learner
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)
(1, 1250, 9)


In [30]:
result_cca_fixed_coefficients[2]

[185, 0.7708333333333334]

In [31]:
result_cca_fixed_coefficients_2 = k_fold_predict(
    input_data, 
    StandardCCAFilter(
        electrodes_name=electrode_list_fbcca,
        start_time_idx=start_time_index,
        stop_time_idx=stop_time_index,
        fit_start_time_idx=125,
        fit_stop_time_idx=1375,
        num_harmonics=5
    )
)

[block 0] | Started
[block 0] | Fit the learner
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
[block 0] | Predict on test data
[block 1] | Started
[block 1] | Fit the learner
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)
(1, 6250, 9)


In [32]:
result_cca_fixed_coefficients_2[2]

[196, 0.8166666666666667]

In [9]:
result_cca_spatio_temporal = test_fit_predict(
    input_data, 
    SpatioTemporalCCA(
        electrodes_name=electrode_list_fbcca,
        start_time_idx=start_time_index,
        stop_time_idx=stop_time_index,
        num_harmonics=3,
        window_gap=0,
        window_length=9,
    )
)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Users/joao.cerqueira/miniforge3/envs/conda-master/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/s2/7jtwsrm527x914rgsrv1q4tm0000gp/T/ipykernel_53185/1936614142.py", line 1, in <module>
    result_cca_spatio_temporal = test_fit_predict(
  File "/Users/joao.cerqueira/miniforge3/envs/conda-master/lib/python3.10/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "/Users/joao.cerqueira/Documents/master/ssvep-bci-project/src/ssvepcca/pipelines.py", line 67, in test_fit_predict
    prediction, predict_proba = learner(score_data)
  File "/Users/joao.cerqueira/Documents/master/ssvep-bci-project/src/ssvepcca/transformers.py", line 347, in __call__
    res = chain_call_transformers(eeg_tensor, *[p.fit for p in self.pipeline])
  File "/Users/joao.cerqueira/Documents/master/ssvep-bci-proj

In [ ]:
assert result_cca_spatio_temporal[2][0] == 234

## Test single obs

In [11]:
sample_data = EEGType(input_data[0, 0, ...], 0, ssvepcca.runtime_configuration.num_samples)

In [12]:
spatioTemporalCCA = SpatioTemporalCCA(
        electrodes_name=electrode_list_fbcca,
        start_time_idx=start_time_index,
        stop_time_idx=1350,
        num_harmonics=3,
        window_gap=0,
        window_length=9,
    )

In [13]:
spatioTemporalCCA(sample_data)

(0,
 array([0.70643494, 0.40332422, 0.38561117, 0.44694709, 0.47583046,
        0.36409108, 0.3395313 , 0.33882736, 0.38364184, 0.31072345,
        0.39069688, 0.39199155, 0.39984519, 0.37682414, 0.36938787,
        0.29413498, 0.42480924, 0.42801206, 0.34618253, 0.40820144,
        0.32554629, 0.34351527, 0.32454922, 0.3040075 , 0.26602904,
        0.31919306, 0.39899897, 0.36089557, 0.31253692, 0.33036269,
        0.33318963, 0.34645732, 0.36526264, 0.38756878, 0.42825313,
        0.37318334, 0.352626  , 0.29875394, 0.36071682, 0.31382585]))

In [14]:
standardCCA = StandardCCA(
    electrodes_name=electrode_list_fbcca,
    start_time_idx=start_time_index,
    stop_time_idx=1350,
    num_harmonics=5
)

In [15]:
standardCCA(sample_data)

(0,
 array([0.53902277, 0.19863025, 0.26279994, 0.25743609, 0.27428473,
        0.20816448, 0.17325782, 0.17051759, 0.21252577, 0.18152629,
        0.2709892 , 0.24746831, 0.23519569, 0.18852543, 0.17374468,
        0.14442727, 0.28871975, 0.29835605, 0.2416075 , 0.29324709,
        0.19976752, 0.18856436, 0.11960307, 0.14777571, 0.19029166,
        0.19136857, 0.24530902, 0.19709482, 0.17788288, 0.20128029,
        0.18843684, 0.17598194, 0.21378851, 0.22848629, 0.30996256,
        0.20461261, 0.20238713, 0.15484384, 0.16768774, 0.1538101 ]))

In [98]:
filterbankCCA = FilterbankCCA(
        electrodes_name=electrode_list_fbcca,
        start_time_idx=0,
        stop_time_idx=1350,
        num_harmonics=5,
        fb_num_subband=3,
        fb_fundamental_freq=8,
        fb_upper_bound_freq=88,
        fb_weight__a=1.25,
        fb_weight__b=0.25,
    )

In [99]:
filterbankCCA(sample_data)

(0,
 array([0.96313407, 0.18711672, 0.16370419, 0.21017937, 0.31685004,
        0.13459886, 0.17442819, 0.14019148, 0.20571232, 0.12285189,
        0.18227744, 0.19098432, 0.12944552, 0.13747828, 0.2088043 ,
        0.13224756, 0.24646671, 0.21266114, 0.14104421, 0.2048877 ,
        0.13142541, 0.14343826, 0.11749778, 0.12972493, 0.1246988 ,
        0.13869433, 0.14709062, 0.18356772, 0.10668786, 0.1562556 ,
        0.17614919, 0.11654782, 0.18218747, 0.19711759, 0.233009  ,
        0.1493272 , 0.10895613, 0.12995588, 0.15381889, 0.11399369]))

In [72]:
window_gap=4
window_length=1
window_gap + window_length

5

In [97]:
a = np.array([1,3,4])
a[np.newaxis, ...].repeat(2, axis=0)

array([[1, 3, 4],
       [1, 3, 4]])

In [61]:
fbSpatioTemporalCCA = FBSpatioTemporalCCA(
        electrodes_name=electrode_list_fbcca,
        start_time_idx=start_time_index,
        stop_time_idx=1350,
        num_harmonics=5,

        fb_num_subband=3,
        fb_fundamental_freq=8,
        fb_upper_bound_freq=88,
        fb_weight__a=1.25,
        fb_weight__b=0.25,

        window_gap=4,
        window_length=1
    )

In [62]:
fbSpatioTemporalCCA(sample_data)

(0,
 array([1.27857169, 0.31677126, 0.35463153, 0.37200337, 0.45058716,
        0.18963709, 0.3120555 , 0.2551005 , 0.33135396, 0.23908524,
        0.26470254, 0.29127721, 0.22879665, 0.2198335 , 0.33683865,
        0.16097931, 0.45991236, 0.33426004, 0.19935047, 0.28159373,
        0.1860854 , 0.20336079, 0.17670041, 0.20508594, 0.20229821,
        0.23192418, 0.28085811, 0.25037573, 0.1671716 , 0.24230598,
        0.27609266, 0.23840252, 0.31056461, 0.29295869, 0.3010567 ,
        0.23570835, 0.18519975, 0.19646926, 0.2761634 , 0.21717634]))

In [60]:
fbSpatioTemporalCCA(sample_data)

(0,
 array([1.2591894 , 0.31985626, 0.35333269, 0.37017179, 0.44895319,
        0.19577337, 0.31791383, 0.25752098, 0.33231118, 0.23596501,
        0.2679568 , 0.29124863, 0.229892  , 0.21914835, 0.33618208,
        0.16678758, 0.44953851, 0.33935102, 0.19554009, 0.28464828,
        0.18792844, 0.20655818, 0.17774682, 0.2077993 , 0.20528085,
        0.23400025, 0.27615336, 0.24880238, 0.16874744, 0.24651083,
        0.2787398 , 0.23715621, 0.31373743, 0.29591386, 0.30676128,
        0.23857684, 0.18171892, 0.19790169, 0.27951507, 0.21677107]))

In [57]:
fbSpatioTemporalCCA.pipeline[0:5]

(<ssvepcca.transformers.ElectrodesFilter at 0x28635d060>,
 <ssvepcca.transformers.FilterbankProjector at 0x28635fbe0>)

In [40]:
list(enumerate(filterbankCCA.pipeline))

[(0, <ssvepcca.transformers.ElectrodesFilter at 0x17f567370>),
 (1, <ssvepcca.transformers.TimeFilter at 0x17733d7e0>),
 (2, <ssvepcca.transformers.FilterbankProjector at 0x17733e410>),
 (3, <ssvepcca.transformers.CCAModeCorrelation at 0x17733fc40>),
 (4, <ssvepcca.transformers.Squeeze at 0x17733fc70>),
 (5, <ssvepcca.transformers.FilterBankPredictProba at 0x17733fca0>)]

In [41]:
list(enumerate(fbSpatioTemporalCCA.pipeline))

[(0, <ssvepcca.transformers.ElectrodesFilter at 0x177335240>),
 (1, <ssvepcca.transformers.TimeFilter at 0x177337640>),
 (2, <ssvepcca.transformers.SpatioTemporalBank at 0x177337dc0>),
 (3, <ssvepcca.transformers.TimeFilter at 0x1773f27d0>),
 (4, <ssvepcca.transformers.FilterbankProjector at 0x1773f3100>),
 (5, <ssvepcca.transformers.CCAModeCorrelation at 0x1773f3940>),
 (6, <ssvepcca.transformers.Squeeze at 0x17f5a2e90>),
 (7, <ssvepcca.transformers.FilterBankPredictProba at 0x17f5a3b20>)]

In [67]:
chain_call_transformers(
    sample_data,
    *filterbankCCA.pipeline[0:3]
).data.shape

(3, 1225, 9)

In [68]:
chain_call_transformers(
    sample_data,
    *fbSpatioTemporalCCA.pipeline[0:5]
).data.shape

(3, 1225, 18)

In [70]:
1350 - start_time_index


1225

## Print algorithms params before saving.

In [14]:
standardCCA = StandardCCA(
    electrodes_name=electrode_list_fbcca,
    start_time_idx=start_time_index,
    stop_time_idx=stop_time_index,
)

In [18]:
standardCCA.__str__()

'StandardCCA'

In [19]:
list(vars(standardCCA))

['start_time_idx',
 'stop_time_idx',
 'electrodes_name',
 'electrodes_index',
 'num_components',
 'num_harmonics',
 'pipeline']

In [20]:
result_cca_single_component = test_fit_predict(
    input_data, 
    standardCCA
)

[block 0] | Started
[block 0] | Fit-predict for target 0
called id  0 , time elapsed: 0.00028083298821002245
called id  1 , time elapsed: 5.832989700138569e-06
called id  2 , time elapsed: 5.707988748326898e-06
called id  3 , time elapsed: 0.06750645799911581
called id  4 , time elapsed: 2.416985807940364e-06
[block 0] | Fit-predict for target 1
called id  0 , time elapsed: 8.791600703261793e-05
called id  1 , time elapsed: 1.834006980061531e-06
called id  2 , time elapsed: 2.582994056865573e-06
called id  3 , time elapsed: 0.044454165996285155
called id  4 , time elapsed: 2.1669839043170214e-06
[block 0] | Fit-predict for target 2
called id  0 , time elapsed: 8.366699330508709e-05
called id  1 , time elapsed: 1.8749851733446121e-06
called id  2 , time elapsed: 2.583983587101102e-06
called id  3 , time elapsed: 0.04394845900242217
called id  4 , time elapsed: 1.4580145943909883e-06
[block 0] | Fit-predict for target 3
called id  0 , time elapsed: 8.458399679511786e-05
called id  1 , ti

In [21]:
list(vars(standardCCA))

['start_time_idx',
 'stop_time_idx',
 'electrodes_name',
 'electrodes_index',
 'num_components',
 'num_harmonics',
 'pipeline']

In [22]:
standardCCA.pipeline

(<ssvepcca.transformers.ElectrodesFilter at 0x137bba320>,
 <ssvepcca.transformers.Squeeze at 0x137bba140>)

In [25]:
standardCCA.__dict__

{'start_time_idx': 125,
 'stop_time_idx': 875,
 'electrodes_name': ('PZ',
  'PO5',
  'PO3',
  'POz',
  'PO4',
  'PO6',
  'O1',
  'Oz',
  'O2'),
 'electrodes_index': [47, 53, 54, 55, 56, 57, 60, 61, 62],
 'num_components': 1,
 'num_harmonics': 3,
 'pipeline': (<ssvepcca.transformers.ElectrodesFilter at 0x137bba320>,
  <ssvepcca.transformers.Squeeze at 0x137bba140>)}

In [30]:
standardCCA.__class__

ssvepcca.transformers.StandardCCA

In [28]:
StandardCCA.__clas

type